import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {Window} from 'happy-dom';
import {database,staff,manifest} from './database-helpers.mjs';
import {createWarehouseHandler} from '../supabase/functions/warehouse-api/handler.mjs';
const base=new URL('../warehouse-project/site/dist/',import.meta.url);
const until=async(fn,message)=>{for(let i=0;i<200;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}assert.fail(typeof message==='function'?message():message);};
test('Arabic interface: real inventory search, inspection, approval, return, personal history and public QR',async t=>{
 const db=await database();t.after(()=>db.close());const admin=await staff(db,'manager');
 const errors=[];
 const rpc=async(name,args)=>{const a=Object.entries(args);return(await db.query(`select public.${name}(${a.map(([k],i)=>`${k} => $${i+1}`).join(',')}) as data`,a.map(([,v])=>typeof v==='object'?JSON.stringify(v):v))).rows[0].data;};
 const handle=createWarehouseHandler({env:()=>undefined,rpc,authenticateAdmin:async(u,p)=>u==='admin'&&p==='test-password'?admin.user.id:null});
 function page(hash=''){
  const w=new Window({url:'http://localhost:8000/warehouse-progect/'+hash,settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true,disableComputedStyleRendering:true}});
  t.after(()=>w.happyDOM.abort());
  w.addEventListener('error',e=>errors.push(e.error||e.message));
  w.fetch=async(url,options)=>handle(new Request(url,{method:options.method,body:options.body,headers:{...options.headers,Origin:'http://localhost:8000'}}));
  w.document.write(readFileSync(new URL('index.html',base),'utf8').replace(/<script[\s\S]*?<\/script>/g,''));
  w.WAREHOUSE_CONFIG={apiUrl:'https://test.invalid/api'};
  w.eval(['warehouse-api.js','vendor/qrcode.js','bravo-contents.js','equipment-photos.js','rb001-view.js','app.js','equipment-search.js','warehouse-management.js'].map(src=>readFileSync(new URL(src,base),'utf8')).join('\n;\n'));
  return w;
 }
 const click=(w,s)=>{const b=w.document.querySelector(s);assert.ok(b,'Missing '+s);assert.ok(!b.disabled,'Disabled '+s);b.click();};
 const fill=(w,s,value)=>{const x=w.document.querySelector(s);assert.ok(x,'Missing '+s);x.value=value;x.dispatchEvent(new w.Event('input',{bubbles:true}));};
 const submit=(w,s)=>w.document.querySelector(s).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
 const login=async(w,adminMode=false)=>{
  if(adminMode)click(w,'[data-wh-login-mode="admin"]');
  fill(w,adminMode?'[name=username]':'[name=name]',adminMode?'admin':'عامل اختبار الواجهة');
  fill(w,adminMode?'[name=password]':'[name=employee_id]',adminMode?'test-password':'54321');
  submit(w,'#wh-login-form');await until(()=>w.document.getElementById('warehouse-access').hidden,()=> 'Login failed: '+w.document.body.textContent+' ERRORS '+errors.map(String).join(','));
 };
 const a=page(),w=page();assert.equal(w.document.documentElement.dir,'rtl');assert.ok(w.document.body.classList.contains('wh-locked'));
 await login(a,true);await login(w);
 const item=manifest.items.find(i=>i.name?.includes('منشار')&&!i.is_group);
 assert.ok(item);const box=manifest.boxes.find(b=>b.id===item.box_id);
 click(a,'[data-wh-view="inventory"]');await until(()=>a.document.querySelector('#wh-inventory-box'),'Inventory did not load');
 const select=a.document.querySelector('#wh-inventory-box');select.value=box.id;select.dispatchEvent(new a.Event('change',{bubbles:true}));
 click(a,`[data-wh-review-item="${item.id}"]`);fill(a,'dialog [name=quantity]','1');fill(a,'dialog [name=condition]','sound');submit(a,'dialog form');
 await until(()=>!a.document.querySelector('dialog'),'Review failed');
 // Re-login reloads server inventory; no local storage is used.
 click(w,'[data-wh-logout]');await until(()=>!w.WarehouseService.user,'Logout failed');await login(w);
 fill(w,'#equipment-query','منشار');assert.ok(w.document.querySelectorAll('[data-equipment-result]').length>0);
 const result=[...w.document.querySelectorAll('#equipment-results > li')].find(li=>li.querySelector(`[data-wh-borrow="${item.id}"]`));
 assert.ok(result);assert.match(result.textContent,/برافو/);assert.match(result.textContent,/المستوى/);assert.match(result.textContent,/متاحة/);
 result.querySelector('[data-equipment-result]').click();await until(()=>w.document.querySelector('.rb-stage'),'Search did not navigate to the case');
 assert.ok(w.document.querySelector(`[data-wh-borrow="${item.id}"]`));
 click(w,'#rb-toggle');await until(()=>w.document.querySelector('.rb-stage .case').getAttribute('aria-expanded')==='true','Box did not open');
 click(w,'#rb-toggle');await until(()=>w.document.querySelector('.rb-stage .case').getAttribute('aria-expanded')==='false','Box did not close');
 click(w,`#app [data-wh-borrow="${item.id}"]`);const unit=w.document.querySelector('dialog input[name=unit_ids]');assert.ok(unit);unit.checked=true;submit(w,'dialog form');
 await until(()=>!w.document.querySelector('dialog'),'Request failed');
 click(a,'[data-wh-view="requests"]');await until(()=>a.document.querySelector('[data-wh-approve]'),'Pending request missing');
 click(a,'[data-wh-approve]');fill(a,'dialog [name=condition-0]','sound');submit(a,'dialog form');await until(()=>!a.document.querySelector('dialog'),'Approval failed');
 click(w,'[data-wh-view="custody"]');await until(()=>w.document.querySelector('[data-wh-return]'),'Custody missing');
 assert.match(w.document.querySelector('#warehouse-panel').textContent,/حالة الخروج: سليمة/);
 click(w,'[data-wh-return]');submit(w,'dialog form');await until(()=>!w.document.querySelector('dialog'),'Return request failed');
 click(a,'[data-wh-refresh]');await until(()=>a.document.querySelector('[data-wh-approve]'),'Return approval missing');click(a,'[data-wh-approve]');
 fill(a,'dialog [name=condition-0]','needs_maintenance');fill(a,'dialog [name=notes-0]','ملاحظة فحص اختبارية في قاعدة مؤقتة');submit(a,'dialog form');await until(()=>!a.document.querySelector('dialog'),'Return approval failed');
 click(w,'[data-wh-refresh]');await until(()=>w.document.querySelector('[data-wh-history="true"]')&&!w.document.querySelector('[data-wh-return]'),'Returned unit still in current custody');
 click(w,'[data-wh-history="true"]');await until(()=>w.document.querySelector('#warehouse-panel').textContent.includes('حالة الإرجاع:'),'History missing');
 assert.match(w.document.querySelector('#warehouse-panel').textContent,/حالة الخروج: سليمة/);
 assert.match(w.document.querySelector('#warehouse-panel').textContent,/حالة الإرجاع: بها عطل وتحتاج صيانة/);
 click(a,'[data-wh-view="map"]');click(a,'[data-action="rb001"]');await until(()=>a.document.querySelector('.rb-stage'),'Existing RB-001 shortcut stopped working');
 const publicPage=page('#box='+box.id);await until(()=>publicPage.document.querySelector('.rb-stage'),'Public QR did not open case');
 assert.equal(publicPage.WarehouseService.user,null);assert.ok(!publicPage.document.body.textContent.includes('54321'));
 click(publicPage,'[data-wh-qr]');assert.match(publicPage.document.querySelector('dialog img').src,/^data:image\/gif;base64,/);
 assert.equal(publicPage.document.querySelector('dialog a').hash,'#box='+box.id);
 click(w,'[data-wh-logout]');await until(()=>!w.WarehouseService.user,'Logout failed');assert.equal(w.document.querySelector('#warehouse-panel').textContent,'');
 assert.equal(w.localStorage.length,0);assert.equal(a.localStorage.length,0);assert.equal(w.sessionStorage.length,0);
 assert.deepEqual(errors,[]);
});
